"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse, parse_qsl, unquote


def _env(*names, default=''):
    for name in names:
        value = os.environ.get(name)
        if value:
            return value
    return default


def _db_from_url(url):
    u = urlparse(url)
    qs = dict(parse_qsl(u.query))
    try:
        port = str(u.port) if u.port else ''
    except ValueError:
        port = ''
    pooler = port == '6543' or 'pgbouncer' in qs
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(u.path.lstrip('/')) or 'postgres',
        'USER': unquote(u.username) if u.username else 'postgres',
        'PASSWORD': unquote(u.password) if u.password else '',
        'HOST': u.hostname or 'localhost',
        'PORT': port or '5432',
        'CONN_MAX_AGE': int(_env('POSTGRES_CONN_MAX_AGE', default='0' if pooler else '60')),
        'OPTIONS': {'sslmode': qs.get('sslmode', 'require')},
        # Supabase pooler (PgBouncer, transaction mode) não suporta cursores server-side
        'DISABLE_SERVER_SIDE_CURSORS': pooler,
    }


_DATABASE_URL = _env(
    'sebo_POSTGRES_PRISMA_URL',
    'sebo_POSTGRES_URL',
    'POSTGRES_PRISMA_URL',
    'POSTGRES_URL',
    'DATABASE_URL',
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-rp*guwebq&-nmz6mblz8v!gk&=_2=l+)2(joe69iun_p+pjzlt')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vendedores',
    'clientes',
    'encomendas',
    'formularios',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# Prioridade: URL completa (Supabase pooler/direta) > variáveis avulsas.
# Aceita os nomes do .env.local do Supabase (prefixo sebo_) e os sem prefixo.

if _DATABASE_URL:
    DATABASES = {'default': _db_from_url(_DATABASE_URL)}
else:
    _pg_host = _env('sebo_POSTGRES_HOST', 'POSTGRES_HOST', default='localhost')
    _pg_port = _env('sebo_POSTGRES_PORT', 'POSTGRES_PORT', default='5432')
    _pg_options = (
        {'sslmode': 'require'}
        if 'supabase.co' in _pg_host or 'supabase.com' in _pg_host
        else {}
    )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _env('sebo_POSTGRES_DATABASE', 'POSTGRES_DATABASE', 'POSTGRES_DB', default='sebo'),
            'USER': _env('sebo_POSTGRES_USER', 'POSTGRES_USER', default='postgres'),
            'PASSWORD': _env('sebo_POSTGRES_PASSWORD', 'POSTGRES_PASSWORD', default='sebo'),
            'HOST': _pg_host,
            'PORT': _pg_port,
            'CONN_MAX_AGE': int(
                _env('POSTGRES_CONN_MAX_AGE', default='0' if _pg_port == '6543' else '60')
            ),
            'OPTIONS': _pg_options,
            'DISABLE_SERVER_SIDE_CURSORS': _pg_port == '6543',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

AUTH_USER_MODEL = 'vendedores.Vendedor'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'login'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
