# Generated by Django 6.1.1 on 2026-10-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encomendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='encomenda',
            index=models.Index(fields=['vendedor', 'status'], name='encomendas__vendedo_801f0a_idx'),
        ),
    ]
