# Generated by Django 6.1.1 on 2026-10-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livrointeresse',
            name='genero',
        ),
        migrations.AddField(
            model_name='livrointeresse',
            name='autor',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
